MATO/Models/Federation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MATO.Models
{
    public class Federation
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "error.message.length")]
        public string Name { get; set; }       

        public Address OfficialAdress { get; set; }

        public Address PostalAdress { get; set; }

        public ICollection<Club> Clubs { get; set; }
    }
}

MATO/Controllers/ClubController.cs
using MATO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.Extensions.Localization;

namespace MATO.Controllers
{    
    public class ClubController : Controller
    {
        private IClubRepository _repository;
        private IFederationRepository _repositoryFederation;

        public ClubController(IClubRepository repository, IFederationRepository repositoryFederation) {            
            _repository = repository;
            _repositoryFederation = repositoryFederation;
        }

        public IActionResult Index() {            
            var data = _repository.GetAllClubs().Result;
            ViewBag.title = "Club List";
            return View(data);            
        }

        [HttpGet]
        public async Task<IActionResult> Add() {
            ViewBag.title = "Add Club";
            ViewBag.federations = await _repositoryFederation.GetSelectListItems();
            return View("Form");
        }

        [HttpPost]
        public async Task<IActionResult> Add(Club newClub) {
            if (ModelState.IsValid) {
                try {                   
                    await _repository.AddClub(newClub);                    
                }
                catch (DbUpdateConcurrencyException) {
                }
                return RedirectToAction("Index");
            }
            ViewBag.title = "Add Club";
            ViewBag.federations = await _repositoryFederation.GetSelectListItems();
            return View("Form", newClub);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {            
            if (id == null)
            {
                return NotFound();
            }
            var club = await _repository.FindClub(id);
            ViewBag.title = "Edit Club";
            ViewBag.federations = await _repositoryFederation.GetSelectListItems();
            return View("Form", club);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Club editedClub)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await TryUpdateModelAsync<Club>(await _repository.FindClub(editedClub.Id));
                    await _repository.SaveChangesAsync();              
                }
                catch (DbUpdateConcurrencyException)
                {
                }
                return RedirectToAction("Index");
            }
            ViewBag.title = "Edit Federation";
            ViewBag.federations = await _repositoryFederation.GetSelectListItems();
            return View("Form");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var federation = await _repository.FindClub(id);
            ViewBag.title = "Delete Club";
            return View("Delete", federation);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _repository.DeleteClub(id);
            return RedirectToAction("Index");
        }
    }
}

MATO/Controllers/FederationController.cs
using MATO.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.Extensions.Localization;

namespace MATO.Controllers
{    
    public class FederationController : Controller
    {
        private IFederationRepository _repository;        

        public FederationController(IFederationRepository repository) {            
            _repository = repository;
        }

        public IActionResult Index() {            
            var data = _repository.GetAllFederations().Result;
            ViewBag.title = "Federation List";
            return View(data);            
        }

        [HttpGet]
        public IActionResult Add() {
            ViewBag.title = "Add Federation";
            return View("Form");
        }

        [HttpPost]
        public async Task<IActionResult> Add(Federation newFederation) {
            if (ModelState.IsValid) {
                try {                   
                    await _repository.AddFederation(newFederation);                    
                }
                catch (DbUpdateConcurrencyException) {
                }
                return RedirectToAction("Index");
            }
            ViewBag.title = "Add Federation";
            return View("Form", newFederation);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {            
            if (id == null)
            {
                return NotFound();
            }
            var federation = await _repository.FindFederation(id);
            ViewBag.title = "Edit Federation";
            return View("Form", federation);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Federation editedFederation)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    await TryUpdateModelAsync<Federation>(await _repository.FindFederation(editedFederation.Id));
                    await _repository.SaveChangesAsync();              
                }
                catch (DbUpdateConcurrencyException)
                {
                }
                return RedirectToAction("Index");
            }
            ViewBag.title = "Edit Federation";
            return View("Form");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var federation = await _repository.FindFederation(id);
            ViewBag.title = "Delete Federation";
            return View("Delete", federation);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _repository.DeleteFederation(id);
            return RedirectToAction("Index");
        }
    }
}

MATO/Views/Federation/Delete.cshtml
@model MATO.Models.Federation

<div class="panel panel-danger">
    <div class="panel-heading">@ViewBag.Title</div>   
    <div class="panel-body">
        <h3>Are you sure you want to delete this ?</h3>
        <form method="post">
            @Html.Partial("FederationViewPartial", Model)             
            <div class="form-group">
                <a asp-controller="Club" asp-action="Index" class="btn btn-default">Cancel</a>
                <input type="submit" value="Delete" class="btn btn-danger" />
            </div>
        </form>
   </div>
</div>

MATO/Views/Federation/Form.cshtml
@model MATO.Models.Federation

@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="panel panel-default">
    <div class="panel-heading">@ViewBag.Title</div>
    <div class="panel-body">
        <form method="post">
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            @{ ViewBag.Title = "General"; }
                            <h4>@ViewBag.Title</h4>
                            @if (ViewBag.Message != null)
                            {
                                <div>@ViewBag.Message</div>
                            }
                            <div asp-validation-summary="ModelOnly"></div>
                            <div class="form-group">
                                <label asp-for="Name"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-muted"></span>
                            </div>                            
                        </div>
                    </div>
                </div>    
                @{ ViewBag.Title = "Official Address"; }
                @Html.EditorFor(Model => Model.OfficialAdress)                
                @{ ViewBag.Title = "Postal Address"; }
                @Html.EditorFor(Model => Model.PostalAdress)
            </div>
            <div class="form-group">
                <a asp-controller="Federation" asp-action="Index" class="btn btn-default">Cancel</a>
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
   </div>
</div>

@*<address asp-for="OfficialAdress" />*@

MATO/Views/Federation/Index.cshtml
@model List<MATO.Models.Federation>
<div class="panel panel-default">
    <div class="panel-heading">@ViewBag.Title</div>
    <div class="panel-body">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>                    
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @{int i = 0;}
                @foreach (var federation in Model)
                {
                    i++;
                    <tr>
                        <th scope="row">@i</th>
                        <td>@federation.Name</td>                       
                        <td>
                            <a class="btn btn-primary" role="button" asp-controller="Federation" asp-action="Edit" asp-route-id="@federation.Id">Edit</a>
                            <a class="btn btn-danger" role="button" asp-controller="Federation" asp-action="Delete" asp-route-id="@federation.Id">Delete</a>
                        </td>
                    </tr>
                }                
            </tbody>
        </table>
        <div class="row">
            <div class="col-lg-3"><a class="btn btn-primary" role="button" asp-controller="Federation" asp-action="Add">Add</a></div>
        </div>
    </div>
</div>